/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as LoginImport } from './routes/login'
import { Route as CreateTaskImport } from './routes/create-task'
import { Route as UpdateTaskTaskImport } from './routes/update-task.$task'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateTaskRoute = CreateTaskImport.update({
  path: '/create-task',
  getParentRoute: () => rootRoute,
} as any)

const UpdateTaskTaskRoute = UpdateTaskTaskImport.update({
  path: '/update-task/$task',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-task': {
      id: '/create-task'
      path: '/create-task'
      fullPath: '/create-task'
      preLoaderRoute: typeof CreateTaskImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/update-task/$task': {
      id: '/update-task/$task'
      path: '/update-task/$task'
      fullPath: '/update-task/$task'
      preLoaderRoute: typeof UpdateTaskTaskImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  CreateTaskRoute,
  LoginRoute,
  TasksRoute,
  UpdateTaskTaskRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/create-task",
        "/login",
        "/tasks",
        "/update-task/$task"
      ]
    },
    "/create-task": {
      "filePath": "create-task.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/update-task/$task": {
      "filePath": "update-task.$task.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
